version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
    - "8080:80"
    depends_on:
      - app
      - db
    networks:
      - desafio-node-network

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - desafio-node-network
    command: node index.js
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-node-network

networks:
  desafio-node-network:
    driver: bridge